# -*- mode: ruby -*-
# vi: set ft=ruby :

#Parte 1 - Vagrant

Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "ThiagoSouza"
      vb.gui = false
      vb.memory = "1024"
    end
    config.vm.network "private_network", ip: "192.168.57.13"
    config.vm.hostname = "ThiagoSouza"
    
    # Configuracao para chamar o Ansible
  
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_zabbix.yml"
    end
  end
    