- name: Set root password localhost
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: root
    login_host: localhost
    login_port: 3306
    state: present
  when: mysql_root_pass is defined
  tags: mysql