# -*- mode: ruby -*-
# vi: set ft=ruby :

#Parte 1 - Vagrant
Vagrant.configure("2") do |config|
    REQUIRED_PLUGINS = %w(vagrant-libvirt)
    exit unless REQUIRED_PLUGINS.all? do |plugin|
      Vagrant.has_plugin?(plugin) || (
        puts "The #{plugin} plugin is required. Please install it with:"
        puts "$ sudo apt install vagrant ruby-libvirt qemu qemu-kvm virtinst libvirt-daemon-system libvirt-daemon libvirt-clients bridge-utils ebtables dnsmasq-base libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev libguestfs-tools -y"
	      puts "$ vagrant plugin install #{plugin}"
        false
      )
    end   
    config.vm.box = "generic/fedora28"
    config.vm.provider :libvirt do |libvirt|
      libvirt.driver = "kvm"
      libvirt.title = "Fedora_pratc05"
      #libvirt.default_prefix = "fedora28_"
      libvirt.memory = "1024"
      libvirt.storage_pool_name = "default"
    end
    config.vm.hostname = "prat05"
  end
    
